#include "DIO.h"

const strDIOConfigType_t astrDIOConfigParameters[DIO_GROUPS_NO] =
{
	{ PD0, INPUT, PULL_UP_ENABLE },
	{ PD1, INPUT, PULL_UP_ENABLE },
	{ PD2, INPUT, PULL_UP_ENABLE },
	{ PD3, INPUT, PULL_UP_ENABLE },
	{ PD4, OUTPUT, NO_CONNECTION },
	{ PD5, OUTPUT, NO_CONNECTION },
	{ PD6, OUTPUT, NO_CONNECTION }
};
